#!/usr/bin/env bash
set -euo pipefail

# Run on a Proxmox VE host as root.
# RouterOS changes are applied only after an explicit confirmation.

[[ $(id -u) -eq 0 ]] || { echo '请在 PVE Shell 以 root 运行。'; exit 1; }
command -v pct >/dev/null || { echo '未检测到 pct，此脚本必须运行在 PVE 主机。'; exit 1; }

ensure_sshpass() {
  if command -v sshpass >/dev/null; then
    return
  fi
  command -v apt-get >/dev/null || { echo '缺少 sshpass，且系统没有 apt-get，无法继续。'; return 1; }
  echo '未检测到 sshpass，正在自动安装...'
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y sshpass
}

ask() { local p=$1 d=${2-} v; read -r -p "$p${d:+ [$d]}：" v; printf '%s' "${v:-$d}"; }
secret() { local v; read -r -s -p "$1：" v; echo >&2; printf '%s' "$v"; }
valid_ip() { [[ $1 =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; }
free_vmid() {
  local n=${1:-100}
  while pct config "$n" >/dev/null 2>&1; do
    n=$((n + 1))
  done
  echo "$n"
}

probe_routeros() {
  local host=$1 port=$2 user=$3 iface=$4 pass=$5 output probe
  probe=${IPTV_STB_PROBE:-$PWD/bin/stb-probe-linux-amd64}
  [[ -x $probe ]] || { echo "缺少抓包工具：$probe"; return 1; }
  ensure_sshpass || return 1
  output=$(mktemp)
  echo '即将抓包 90 秒，请现在重启或重新连接实体机顶盒。'
  SSHPASS="$pass" "$probe" -router "$host" -router-port "$port" -router-user "$user" -router-password-env SSHPASS -interface "$iface" -duration 90 | tee "$output"
  IPTV_PROBE_VLAN=$(sed -n 's/^  vlan: "\([0-9]*\)"/\1/p' "$output")
  IPTV_OPTION125=$(sed -n 's/^  option125: "\([0-9A-Fa-f]*\)"/\1/p' "$output")
  [[ -n $IPTV_PROBE_VLAN ]] || { echo '抓包未识别 VLAN，拒绝继续自动配置。'; rm -f "$output"; return 1; }
  echo "抓包识别：VLAN=$IPTV_PROBE_VLAN Option125=${IPTV_OPTION125:-未识别}"
  rm -f "$output"
}

scan_routeros() {
  local host=$1 port=$2 user=$3 pass=$4 scan
  ensure_sshpass || return 1
  scan=$(mktemp)
  SSHPASS="$pass" sshpass -e ssh -o StrictHostKeyChecking=no -p "$port" "$user@$host" \
    '/interface bridge print detail; /interface bridge port print detail; /interface vlan print detail; /ip dhcp-client print detail; /ip dhcp-server option print detail; /routing igmp-proxy interface print detail; /ip dhcp-server lease print detail; /ip arp print detail' | tee "$scan"
  echo "RouterOS 扫描结果已保存：$scan"
  ROUTEROS_SCAN_FILE=$scan
}

free_routeros_ip() {
  local host=$1 port=$2 user=$3 pass=$4 base=$5 start=${6:-90} used n ip
  used=$(SSHPASS="$pass" sshpass -e ssh -o StrictHostKeyChecking=no -p "$port" "$user@$host" \
    '/ip dhcp-server lease print detail; /ip arp print detail' 2>/dev/null | \
    sed -nE 's/.*address=([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+).*/\1/p' | sort -u)
  for ((n=start; n<255; n++)); do
    ip="$base.$n"
    if [[ "$ip" != "$base.1" && "$ip" != "$base.222" ]] && ! grep -qx "$ip" <<<"$used"; then
      echo "$ip"
      return 0
    fi
  done
  return 1
}

routeros_menu() {
  local host port user pass iface wan bridge v85 v51 option125
  host=$(ask 'RouterOS 地址' '192.168.100.1'); port=$(ask 'SSH 端口' '1314'); user=$(ask 'SSH 用户名' 'david_ni')
  iface=$(ask '连接实体机顶盒的 RouterOS 物理端口' 'ether3_lan')
  wan=$(ask '上海电信 IPTV 上联/专网端口' 'ether5_wan')
  bridge=$(ask 'IPTV Bridge 名称' 'bridge_iptv'); v85=$(ask 'LAN IPTV VLAN' '85'); v51=$(ask 'LAN 管理/控制 VLAN' '51')
  option125=$(ask 'DHCP Option 125 内容（十六进制，留空不改）' '')
  pass=$(secret 'RouterOS 密码')
  probe_routeros "$host" "$port" "$user" "$iface" "$pass" || return
  v85=${IPTV_PROBE_VLAN:-$v85}; option125=${IPTV_OPTION125:-$option125}
  local cmds tmp
  tmp=$(mktemp)
  cat >"$tmp" <<EOS
# generated by pve-iptv-prep.sh
/interface bridge
:if ([:len [/interface bridge find where name="$bridge"]] = 0) do={add name=$bridge vlan-filtering=yes comment="iptv-spider"}
/interface vlan
add interface=$bridge name=pon-vlan$v85 vlan-id=$v85 comment="Shanghai Telecom IPTV"
add interface=$bridge name=pon-vlan$v51 vlan-id=$v51 comment="Shanghai Telecom IPTV"
/interface bridge port
add bridge=$bridge interface=$wan
add bridge=$bridge interface=$iface
/interface bridge vlan
add bridge=$bridge tagged=$bridge,$wan vlan-ids=$v85
add bridge=$bridge tagged=$bridge,$wan vlan-ids=$v51
/ip dhcp-client
add interface=pon-vlan$v85 add-default-route=no use-peer-dns=no comment="IPTV DHCP"
/ip firewall nat
add chain=srcnat src-address=30.181.0.0/16 out-interface=pon-vlan$v85 action=masquerade comment="iptv-spider IPTV SNAT"
/routing igmp-proxy interface
add interface=$wan upstream=yes
add interface=$bridge upstream=no
EOS
  if [[ -n $option125 ]]; then cat >>"$tmp" <<EOS
/ip dhcp-server option
add name=iptv-option125 code=125 value=0x$option125 comment="Shanghai Telecom IPTV Option125"
EOS
  fi
  echo; echo '将执行以下 RouterOS 配置：'; cat "$tmp"; echo
  [[ "$(ask '确认执行？输入 YES' 'NO')" =~ ^[Yy][Ee][Ss]$ ]] || { rm -f "$tmp"; echo '已取消。'; return 0; }
  if command -v sshpass >/dev/null; then
    SSHPASS="$pass" sshpass -e ssh -o StrictHostKeyChecking=no -p "$port" "$user@$host" <"$tmp"
  else
    echo '未安装 sshpass，改为输出命令文件，请手工执行：'; cat "$tmp"
  fi
  rm -f "$tmp"
  echo '注意：Option 125 通常还需要绑定到实际 DHCP Server/Network；请根据 RouterOS 现有 DHCP 结构补充绑定。'
}

ct_menu() {
  local storage template vmid hostname ip gw bridge tag mem disk cores password base host port user pass
  host=$(ask 'RouterOS 地址' '192.168.100.1'); port=$(ask 'SSH 端口' '1314'); user=$(ask 'SSH 用户名' 'david_ni'); pass=$(secret 'RouterOS 密码')
  scan_routeros "$host" "$port" "$user" "$pass"
  storage=$(ask 'PVE 存储' 'local'); hostname=$(ask 'CT 主机名' 'iptv-spider'); bridge=$(ask 'PVE IPTV Bridge' 'vmbr0v85'); tag=$(ask 'VLAN Tag（若 bridge 已解包则留空）' '')
  mem=$(ask '内存 MB' '2048'); disk=$(ask '磁盘 GB' '16'); cores=$(ask 'CPU 核数' '2'); base=$(ask 'IP 网段前三段' '30.181.165'); gw=$(ask 'CT 网关（RouterOS IPTV DHCP 地址）' '30.181.165.222')
  vmid=$(free_vmid 100)
  echo "PVE 自动选择空闲 CT ID：$vmid"
  ip=$(free_routeros_ip "$host" "$port" "$user" "$pass" "$base" 2) || { echo 'RouterOS 未找到空闲 IPTV IP。'; return; }
  template=$(find /var/lib/vz/template/cache /mnt/pve/*/template/cache -maxdepth 1 -type f \( -name 'debian-12-standard*.tar.zst' -o -name 'debian-12-standard*.tar.xz' \) 2>/dev/null | head -1 || true)
  if [[ -z $template ]]; then
    echo '未找到 Debian 12 CT 模板，尝试下载。'
    pveam update
    template=$(pveam available --section system | awk '/debian-12-standard/ {print $2; exit}')
    [[ -n $template ]] || { echo '无法找到 Debian 12 模板。'; return 1; }
    pveam download "$storage" "$template"
    template="/var/lib/vz/template/cache/$template"
  fi
  password=$(secret 'CT root 密码')
  local net="name=eth0,bridge=$bridge,ip=$ip/16,gw=$gw"
  [[ -n $tag ]] && net+=",tag=$tag"
  echo "创建 CT $vmid：$ip，模板 $template，网络 $net"
  [[ "$(ask '确认创建？输入 YES' 'NO')" =~ ^[Yy][Ee][Ss]$ ]] || { echo '已取消。'; return 0; }
  if pct status "$vmid" >/dev/null 2>&1; then
    echo "CT $vmid 已存在，停止创建。请重新运行菜单 2 选择下一个空闲 ID。"
    return 0
  fi
  pct create "$vmid" "$template" --hostname "$hostname" --rootfs "$storage:${disk}" --memory "$mem" --cores "$cores" --password "$password" --net0 "$net" --unprivileged 1 --features nesting=1 --onboot 1
  pct set "$vmid" --description 'IPTV Spider prepared by pve-iptv-prep.sh'
  pct start "$vmid"
  pct exec "$vmid" -- sh -c 'mkdir -p /etc/ssh/sshd_config.d && printf "%s\n" "PermitRootLogin yes" "PasswordAuthentication yes" > /etc/ssh/sshd_config.d/99-iptv-spider-root-login.conf && if command -v systemctl >/dev/null 2>&1 && systemctl is-enabled --quiet ssh 2>/dev/null; then systemctl restart ssh; elif command -v systemctl >/dev/null 2>&1 && systemctl is-enabled --quiet sshd 2>/dev/null; then systemctl restart sshd; fi'
  echo; echo "CT 已创建：VMID=$vmid IP=$ip 网关=$gw Bridge=$bridge"
  echo 'root 已启用密码登录；密码为本次创建时输入的 root 密码。'
  echo "下一步：在该 CT 内运行 IPTV Spider 安装程序，并通过 RouterOS 抓取机顶盒参数。"
}

while true; do
  echo; echo '上海电信 IPTV Spider 前置准备'; echo '1) 配置 RouterOS IPTV VLAN/Bridge/DHCP/IGMP Proxy'; echo '2) 创建 IPTV 专网 CT'; echo '0) 退出'
  case "$(ask '请选择' '0')" in 1) routeros_menu;; 2) ct_menu;; 0) exit 0;; *) echo '无效选择。';; esac
done
